### ISSUE TITLE
OmegaTrajectorySegmentation segmentation analysis not saved

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#155]
[TRANSPOSED_SMSS_MIXED_2.txt](https://github.com/OmegaProject/Omega/files/800501/TRANSPOSED_SMSS_MIXED_2.txt)

While segmenting an imported artificial trajectory segmentation results are not saved.
When saving, the display resets to the unsegmented trajectory and in the: "Select Segmentation Run", the menu displays only "Default Segmentation Run" and "Unsaved Segmentation"

**Comment by Akramhar** [comment]
The problem here is only regarding IMPORTED data because we are missing an EXPERIMENTER that we usually obtain from the connection to OMERO. 

I'm going to fix this by using the DEFAULT EXPERIMENTER when no EXPERIMENTER is found.
You can avoid this problem by loggin in OMERO before using the IMPORTER.

This problem should be closed and a new issue should be open to discuss how to handle EXPERIMENTER when working offline.

**Comment by Akramhar** [comment]
Should be fixed.
Before closing the new issue should be open.

**Comment by strambc** [comment]
Solved
