### ISSUE TITLE
OmegaTrackingMeasures_Motion Type problems when unassigned segment present

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#176]
An unassigned segment is displayed in the 
Trajectory plot + Legend
MSD legend but not plot
Not at all in MSS and Scatter plot.

This applies to different segmentation runs when an unassigned segment is present.

**Comment by strambc** [comment]
Same thing happens if the same short segment is assigned a color.
![2017-03-10_segmented but too short](https://cloud.githubusercontent.com/assets/4050585/23812462/a4c9e81c-05a8-11e7-9073-c915f63ff4ae.png)

**Comment by strambc** [comment]
It appears to be a problem of length of the segment.
What is the minimum? Is this a glitch or is it intentional

![2017-03-10_segmented but too short _v02](https://cloud.githubusercontent.com/assets/4050585/23812577/1a198a00-05a9-11e7-8870-2fa9ab36e2d4.png)

**Comment by strambc** [comment]
It would be much better to do the following as a DEFAULT SETTINGS
-- do not exclude the segment based on length (NICE TO HAVE: a parameter in which the user can chose to do it if needed).
-- DO EXCLUDE un-assigned segments and do not plot them on motion type graph

**Comment by Akramhar** [comment]
so the problem is that all the values computed (MSD MSS and Phase Space) depend on the length of the segment due to the window size (windows size 3 for example require at least 3 points to work if im not wrong).
in omega-0.26 I fixed in this way: every segments is displayed in the track graph, segments that have not enough point are not displayed in the other graphs and the legend doesn't show up in the other graph either now

**Comment by strambc** [comment]
OK sounds good.
Could it be possible to put a tool tip or warning somewhere to alert users that some of the trajectory segments were not displayed because too short...
It could be static.

**Comment by strambc** [comment]
This issue was closed and replaced by #248
