### ISSUE TITLE
TrackingMeasures: Physical Size not taken into account

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#206]
I verified in the velocity measurements that the physical T is not taken into account during calculation.
This should be verified for the other measurements too.

This needs to be discussed and elaborated more!

**Comment by Akramhar** [comment]
should be resolved now

**Comment by strambc** [comment]
What version is this solved in? 
I do not see anything past v30

**Comment by Akramhar** [comment]
next version, 0.31

**Comment by strambc** [comment]
This has to be CHECKED AFTER MOSAIC plugin integration in OMEGA is fixed.

**Comment by strambc** [comment]
This issue was tested in depth using Velocity Measures.
Physical units are now taken into account, therefore this issue was closed. 
However there is an issue about when physical units are set, before import into OMEGA, after import but before SPT or after SPT...
For this rason a new issue was opened that inherits from this.
#364

[2018-10-15_Issue #206_tests.xlsx](https://github.com/OmegaProject/Omega/files/2489395/2018-10-15_Issue.206_tests.xlsx)
