### ISSUE TITLE
 PL results table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#257]
# Results summary

- [x] ParticlesLinkingRun ID --> Linking Run ID
- [x] Tracks --> Total number of trajectories
- [ ] Z-section to analyze --> Analyzed Z-plane
- [ ] Channel to analyze --> Analyzed Channel

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY ARE SHOWN]**)

# Results table
- [x] **ID --> when not available change -1 --> NA**

Track --> Trajectory name

- [x] Column order should be: ID, Trajectory name, Time point, X, Y, Z, C, (NPscore)
- [x] Z column is missing.
- [x] C column should be added.
- [x] NPscore column is missing (not sure if this belongs to PD or PL)

(see screen shot and #256)

![screen shot 2017-05-02 at 17 45 14](https://cloud.githubusercontent.com/assets/4050585/25640816/22d65710-2f5f-11e7-9d14-5c599d9f400d.png)

**Comment by Akramhar** [comment]
@strambc 
In this case our results viewer is going to be different because a lot the these information are already displayed in the detection viewer.
For linking our viewer is currently displaying:
Particle ID, Time Point, X, Y, Z, C, Track ID, Track name.
As you can see there is already a certain degree of redundancy in the information displayed.
If we add all the information contained in the Detection in the this view what's the point of having 2 distinct view?

Additionally the "additional values" part (m0, ..., NPScore) are bound to the detection results, to display these information the linking viewer I would have to duplicate or create a connection bridge between the 2 data package (detection-linking) that at the moment is not existing. 
Let me know if you need clarification about this point :)

**Comment by strambc** [comment]
Regarding NPScore etc.
I already knew that m0 etc. is part of PD.
I was not sure about NPScore and that is why I added it here as well.
Disregard this portion of the issue.

**Comment by strambc** [comment]
Regarding data duplication concern:

If you think about it, the linking results are a massive duplication of the PD results. The only difference being that bright spots identified by PD have now been assigned to trajectories.
So what I am asking is not much of a difference, I just want to make it easier for users to gather the results they need.
So having clarified that m0,1,2,3 and 4 and NPScore should be disregarded for the PL table, all I am asking for is to add Z and C, which is not much more of a duplication than already necessary. However it does provide much desired usability to the scientist.
This is my rationale for asking for this change.

**Comment by Akramhar** [comment]
I agree.
My issue about replication was about the additional data.

**Comment by Akramhar** [comment]
should be solved in omega-0.35

**Comment by strambc** [comment]
All issues that are not checked require attention.

**Comment by Akramhar** [comment]
should be fixed in omega-0.36
in case something is still wrong, close this issue and open a new one

**Comment by Akramhar** [comment]
I added track length
